name: ConodiaInvest
version: 1.0.0
author: PandaGuerrier
main: fr.pandaguerrier.conodiainvest.ConodiaInvest
commands:
  invest:
    description: Permet d'ouvrir le menu principal.
    aliases: [i, invests]

  